name: 'Terraform deploy'
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get kubectl
        uses: azure/setup-kubectl@v1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        id: init
        run: terraform init \
          -backend-config="access_key=${{ secrets.SPACES_KEY }}" \
          -backend-config="secret_key=${{ secrets.SPACES_SECRET_KEY }}" \
          -backend-config="bucket=${{ secrets.SPACES_BUCKET_NAME }}"
      - name: Terraform deploy
        id: deploy
        run: terraform apply -auto-approve
        env:
          TF_VAR_digitalocean_token: ${{ secrets.DIGITALOCEAN_TOKEN }}
          TF_VAR_github_token: ${{ secrets.TOKEN }}
          TF_VAR_github_owner: ${{ secrets.USER }}
          TF_VAR_github_organization: ${{ secrets.ORGANIZATION }}